-- Migration: 002_seed (part 3)
-- Activity log: 100+ rows spanning 30+ days
-- Northside Social cross-tenant data

-- ── Activity Log ─────────────────────────────────────────────────────────
-- September 2026 activity trail for Ashmeet SMMA

insert into activity_log (id, agency_id, actor_id, actor_type, entity_type, entity_id, action, from_state, to_state, metadata, created_at) values
  -- September 1-5
  ('act-1',  'ag-1', 'u-1', 'user', 'client',           'cl-1', 'viewed',    null,             null,             '{"tab":"overview"}',                                                         '2026-09-01T08:00:00Z'),
  ('act-2',  'ag-1', 'u-1', 'user', 'client',           'cl-1', 'status_changed', null,          'active',         null,                                                                          '2026-09-01T08:05:00Z'),
  ('act-3',  'ag-1', 'u-2', 'user', 'content_item',     'ci-1', 'created',   null,             'planned',        '{"title":"Smile makeover before/after reel"}',                                '2026-09-01T09:00:00Z'),
  ('act-4',  'ag-1', 'u-2', 'user', 'content_item',     'ci-1', 'status_changed', 'planned',    'calendar_approved', null,                                                                  '2026-09-01T09:30:00Z'),
  ('act-5',  'ag-1', 'u-2', 'user', 'monthly_plan',     'mp-1', 'created',   null,             'draft',         '{"month":"2026-09"}',                                                        '2026-09-01T10:00:00Z'),
  ('act-6',  'ag-1', 'u-2', 'user', 'monthly_plan',     'mp-1', 'status_changed', 'draft',      'sent_to_client', null,                                                                      '2026-09-01T11:00:00Z'),
  ('act-7',  'ag-1', 'u-2', 'user', 'shoot',            'sh-1', 'created',   null,             'scheduled',     '{"title":"Ramana Dental — Sept shoot","scheduled_start":"2026-09-22T09:00:00Z"}', '2026-09-02T09:00:00Z'),
  ('act-8',  'ag-1', 'u-3', 'user', 'content_item',     'ci-6', 'created',   null,             'planned',        '{"title":"Showroom walkthrough reel"}',                                       '2026-09-02T10:00:00Z'),
  ('act-9',  'ag-1', 'u-2', 'user', 'content_item',     'ci-6', 'assigned',  null,             null,             '{"assigned_editor_id":"u-5"}',                                               '2026-09-02T10:30:00Z'),
  ('act-10', 'ag-1', 'u-3', 'user', 'content_item',     'ci-14', 'created',  null,             'planned',        '{"title":"Diwali offer reel"}',                                              '2026-09-03T08:00:00Z'),
  ('act-11', 'ag-1', 'u-4', 'user', 'content_item',     'ci-18', 'created',  null,             'planned',        '{"title":"New season menu reel"}',                                           '2026-09-03T09:00:00Z'),
  ('act-12', 'ag-1', 'u-2', 'user', 'content_item',     'ci-6', 'status_changed', 'calendar_approved', 'shoot_scheduled', null,                                                              '2026-09-03T10:00:00Z'),
  -- September 6-10
  ('act-13', 'ag-1', 'u-5', 'user', 'deliverable_version', 'dv-4', 'uploaded', null,          null,            '{"version":1,"file_size_bytes":52428800}',                                    '2026-09-06T14:00:00Z'),
  ('act-14', 'ag-1', 'u-2', 'user', 'approval_link',     'al-1', 'created',   null,             null,            '{"content_item_id":"ci-6","version_id":"dv-4"}',                             '2026-09-06T15:00:00Z'),
  ('act-15', 'ag-1', null, 'client', 'approval_link',    'al-1', 'viewed',    null,             null,            '{"client_name":"Ramana Dental"}',                                            '2026-09-07T08:00:00Z'),
  ('act-16', 'ag-1', null, 'client', 'approval_link',    'al-1', 'responded', null,             'approved',      '{"client_name":"Ramana Dental"}',                                            '2026-09-07T08:30:00Z'),
  ('act-17', 'ag-1', 'u-2', 'user', 'deliverable_version', 'dv-4', 'status_changed', 'submitted', 'client_approved', null,                                                              '2026-09-07T09:00:00Z'),
  ('act-18', 'ag-1', 'u-2', 'user', 'content_item',     'ci-6', 'status_changed', 'shoot_scheduled', 'cut_submitted', null,                                                              '2026-09-07T10:00:00Z'),
  ('act-19', 'ag-1', 'u-2', 'user', 'content_item',     'ci-6', 'status_changed', 'cut_submitted', 'internally_approved', null,                                                          '2026-09-08T09:00:00Z'),
  ('act-20', 'ag-1', 'u-5', 'user', 'deliverable_version', 'dv-5', 'uploaded', null,          null,            '{"version":1,"file_size_bytes":67108864}',                                    '2026-09-09T11:00:00Z'),
  ('act-21', 'ag-1', 'u-2', 'user', 'post_schedule',    'ps-1', 'created',   null,             null,            '{"content_item_id":"ci-6","scheduled_at":"2026-09-02T10:00:00Z"}',           '2026-09-09T14:00:00Z'),
  -- September 11-15
  ('act-22', 'ag-1', 'u-7', 'user', 'shoot',            'sh-2', 'created',   null,             'scheduled',     '{"title":"Ramana Dental — Oct prep"}',                                       '2026-09-11T09:00:00Z'),
  ('act-23', 'ag-1', 'u-2', 'user', 'shoot',            'sh-2', 'status_changed', 'scheduled', 'completed',    '{"location":"Ramana Dental Clinic, Ludhiana"}',                              '2026-09-11T12:00:00Z'),
  ('act-24', 'ag-1', 'u-7', 'user', 'content_item',     'ci-4', 'status_changed', 'planned',    'shoot_scheduled', null,                                                                  '2026-09-12T08:00:00Z'),
  ('act-25', 'ag-1', 'u-7', 'user', 'content_item',     'ci-4', 'status_changed', 'shoot_scheduled', 'raw_uploaded', null,                                                              '2026-09-12T14:00:00Z'),
  ('act-26', 'ag-1', 'u-7', 'user', 'shoot',            'sh-2', 'status_changed', 'completed',  'raw_uploaded',  null,                                                                      '2026-09-12T15:00:00Z'),
  ('act-27', 'ag-1', 'u-2', 'user', 'content_item',     'ci-2', 'status_changed', 'calendar_approved', 'shoot_scheduled', null,                                                           '2026-09-12T10:00:00Z'),
  ('act-28', 'ag-1', 'u-4', 'user', 'content_item',     'ci-22', 'created',  null,             'planned',        '{"title":"Founder story"}',                                                 '2026-09-13T09:00:00Z'),
  ('act-29', 'ag-1', 'u-5', 'user', 'deliverable_version', 'dv-1', 'uploaded', null,          null,            '{"version":1,"file_size_bytes":52428800}',                                    '2026-09-13T14:00:00Z'),
  ('act-30', 'ag-1', 'u-2', 'user', 'content_item',     'ci-1', 'status_changed', 'shoot_scheduled', 'with_editor',  null,                                                                      '2026-09-13T15:00:00Z'),
  ('act-31', 'ag-1', 'u-3', 'user', 'shoot',            'sh-3', 'created',   null,             'scheduled',     '{"title":"Sandhu Interiors — Sept"}',                                       '2026-09-14T09:00:00Z'),
  -- September 16-20
  ('act-32', 'ag-1', 'u-2', 'user', 'content_item',     'ci-1', 'status_changed', 'with_editor', 'cut_submitted', null,                                                                      '2026-09-16T10:00:00Z'),
  ('act-33', 'ag-1', 'u-2', 'user', 'content_item',     'ci-1', 'status_changed', 'cut_submitted', 'changes_requested', '{"reason":"Audio levels off"}',                                             '2026-09-16T11:00:00Z'),
  ('act-34', 'ag-1', 'u-5', 'user', 'deliverable_version', 'dv-2', 'uploaded', null,          null,            '{"version":2,"file_size_bytes":55050240}',                                    '2026-09-16T14:00:00Z'),
  ('act-35', 'ag-1', 'u-2', 'user', 'content_item',     'ci-1', 'status_changed', 'changes_requested', 'internally_approved', null,                                                           '2026-09-17T09:00:00Z'),
  ('act-36', 'ag-1', 'u-2', 'user', 'approval_link',    'al-1', 'created',   null,             null,            '{"content_item_id":"ci-1","version_id":"dv-2"}',                             '2026-09-17T10:00:00Z'),
  ('act-37', 'ag-1', null, 'client', 'approval_link',    'al-4', 'viewed',    null,             null,            '{"client_name":"Basil Cafe"}',                                               '2026-09-17T08:00:00Z'),
  ('act-38', 'ag-1', null, 'client', 'approval_link',    'al-4', 'responded', null,             'changes',       '{"client_name":"Basil Cafe","comment":"Add logo overlay"}',                  '2026-09-17T08:30:00Z'),
  ('act-39', 'ag-1', 'u-2', 'user', 'content_item',     'ci-1', 'status_changed', 'internally_approved', 'with_client', null,                                                               '2026-09-17T11:00:00Z'),
  ('act-40', 'ag-1', 'u-5', 'user', 'deliverable_version', 'dv-3', 'uploaded', null,          null,            '{"version":3,"file_size_bytes":55706624}',                                    '2026-09-17T14:00:00Z'),
  ('act-41', 'ag-1', 'u-3', 'user', 'content_item',     'ci-14', 'status_changed', 'cut_submitted', 'client_changes', '{"reason":"Add tagline"}',                                                     '2026-09-17T10:00:00Z'),
  -- September 21-23
  ('act-42', 'ag-1', 'u-3', 'user', 'shoot',            'sh-3', 'status_changed', 'scheduled',  'completed',     '{"location":"Sandhu Interiors Showroom"}',                                    '2026-09-24T18:00:00Z'),
  ('act-43', 'ag-1', 'u-8', 'user', 'content_item',     'ci-11', 'status_changed', 'shoot_scheduled', 'raw_uploaded', null,                                                               '2026-09-24T16:00:00Z'),
  ('act-44', 'ag-1', 'u-8', 'user', 'shoot',            'sh-3', 'status_changed', 'completed',  'raw_uploaded',  null,                                                                      '2026-09-24T17:00:00Z'),
  ('act-45', 'ag-1', 'u-3', 'user', 'content_item',     'ci-12', 'status_changed', 'planned',    'shoot_scheduled', null,                                                                  '2026-09-22T09:00:00Z'),
  ('act-46', 'ag-1', 'u-7', 'user', 'shoot',            'sh-1', 'status_changed', 'scheduled',  'completed',     null,                                                                      '2026-09-22T13:00:00Z'),
  ('act-47', 'ag-1', 'u-7', 'user', 'shoot',            'sh-1', 'status_changed', 'completed',  'raw_uploaded',  '{"drive_folder_id":"sh1-drive-folder"}',                                     '2026-09-22T14:00:00Z'),
  ('act-48', 'ag-1', 'u-2', 'user', 'content_item',     'ci-5',  'status_changed', 'with_client', 'scheduled',    null,                                                                      '2026-09-22T15:00:00Z'),
  ('act-49', 'ag-1', 'u-2', 'user', 'post_schedule',    'ps-5', 'created',   null,             null,            '{"content_item_id":"ci-5","scheduled_at":"2026-09-26T16:00:00Z"}',           '2026-09-22T15:30:00Z'),
  ('act-50', 'ag-1', 'u-4', 'user', 'content_item',     'ci-18', 'status_changed', 'cut_submitted', 'internally_approved', null,                                                              '2026-09-23T09:00:00Z'),
  ('act-51', 'ag-1', 'u-2', 'user', 'content_item',     'ci-9',  'status_changed', 'planned',     'posted',        null,                                                                      '2026-09-23T10:00:00Z'),
  ('act-52', 'ag-1', 'u-2', 'user', 'post_schedule',    'ps-6', 'created',   null,             null,            '{"content_item_id":"ci-9","scheduled_at":"2026-09-23T09:00:00Z"}',           '2026-09-23T10:30:00Z'),
  ('act-53', 'ag-1', 'u-2', 'user', 'content_item',     'ci-10', 'status_changed', 'planned',     'posted',        null,                                                                      '2026-09-23T11:00:00Z'),
  -- September 24-30
  ('act-54', 'ag-1', 'u-8', 'user', 'content_item',     'ci-11', 'status_changed', 'raw_uploaded', 'with_editor',  null,                                                                      '2026-09-25T09:00:00Z'),
  ('act-55', 'ag-1', 'u-5', 'user', 'content_item',     'ci-11', 'assigned',  null,             null,            '{"assigned_editor_id":"u-5"}',                                              '2026-09-25T09:30:00Z'),
  ('act-56', 'ag-1', 'u-5', 'user', 'deliverable_version', 'dv-5', 'uploaded', null,          null,            '{"version":1,"file_size_bytes":67108864}',                                    '2026-09-25T14:00:00Z'),
  ('act-57', 'ag-1', 'u-4', 'user', 'content_item',     'ci-5',  'status_changed', 'internally_approved', 'with_client', null,                                                               '2026-09-25T10:00:00Z'),
  ('act-58', 'ag-1', 'u-4', 'user', 'approval_link',    'al-3', 'created',   null,             null,            '{"content_item_id":"ci-5"}',                                                 '2026-09-25T11:00:00Z'),
  ('act-59', 'ag-1', null, 'client', 'approval_link',    'al-3', 'responded', null,             'approved',     '{"client_name":"Basil Cafe"}',                                               '2026-09-25T12:00:00Z'),
  ('act-60', 'ag-1', 'u-4', 'user', 'content_item',     'ci-5',  'status_changed', 'with_client', 'client_approved', null,                                                                '2026-09-25T12:30:00Z'),
  ('act-61', 'ag-1', 'u-4', 'user', 'content_item',     'ci-5',  'status_changed', 'client_approved', 'scheduled',    null,                                                                      '2026-09-25T13:00:00Z'),
  ('act-62', 'ag-1', 'u-3', 'user', 'content_item',     'ci-16', 'status_changed', 'cut_submitted', 'with_client',  null,                                                                      '2026-09-26T09:00:00Z'),
  ('act-63', 'ag-1', 'u-3', 'user', 'content_item',     'ci-15', 'status_changed', 'with_client', 'posted',        null,                                                                      '2026-09-26T10:00:00Z'),
  ('act-64', 'ag-1', 'u-4', 'user', 'post_schedule',    'ps-10', 'created',  null,             null,            '{"content_item_id":"ci-16","scheduled_at":"2026-09-28T11:00:00Z"}',          '2026-09-26T11:00:00Z'),
  ('act-65', 'ag-1', 'u-4', 'user', 'content_item',     'ci-19', 'status_changed', 'planned',      'with_editor',   null,                                                                      '2026-09-26T14:00:00Z'),
  ('act-66', 'ag-1', 'u-5', 'user', 'content_item',     'ci-19', 'assigned',  null,             null,            '{"assigned_editor_id":"u-6"}',                                              '2026-09-26T14:30:00Z'),
  -- August background activity
  ('act-67', 'ag-1', 'u-1', 'user', 'client',           'cl-2', 'created',   null,             null,            '{"name":"Grover Motors","handle":"@grovermotors"}',                          '2026-08-15T10:00:00Z'),
  ('act-68', 'ag-1', 'u-1', 'user', 'client',           'cl-4', 'created',   null,             null,            '{"name":"Khanna Jewellers","handle":"@khannajewellers"}',                    '2026-08-20T14:00:00Z'),
  ('act-69', 'ag-1', 'u-1', 'user', 'client',           'cl-5', 'created',   null,             null,            '{"name":"Basil Cafe","handle":"@basil.ldh"}',                               '2026-08-22T09:00:00Z'),
  ('act-70', 'ag-1', 'u-1', 'user', 'client',           'cl-6', 'created',   null,             null,            '{"name":"Verdant Gym","handle":"@verdant.fit"}',                            '2026-09-10T11:00:00Z'),
  ('act-71', 'ag-1', 'u-2', 'user', 'monthly_plan',     'mp-1', 'approved', null,              'approved',      '{"month":"2026-09","client_id":"cl-1"}',                                    '2026-08-28T16:00:00Z'),
  ('act-72', 'ag-1', 'u-2', 'user', 'monthly_plan',     'mp-2', 'approved', null,              'approved',      '{"month":"2026-09","client_id":"cl-2"}',                                    '2026-08-25T15:00:00Z'),
  ('act-73', 'ag-1', 'u-3', 'user', 'monthly_plan',     'mp-3', 'approved', null,              'approved',      '{"month":"2026-09","client_id":"cl-3"}',                                    '2026-08-30T16:00:00Z'),
  ('act-74', 'ag-1', 'u-2', 'user', 'content_item',     'ci-3', 'created',  null,             'planned',        '{"title":"Why Ramana Dental?"}',                                            '2026-08-25T09:00:00Z'),
  ('act-75', 'ag-1', 'u-3', 'user', 'content_item',     'ci-7', 'created',  null,             'planned',        '{"title":"Service package explainer"}',                                     '2026-08-20T10:00:00Z'),
  ('act-76', 'ag-1', 'u-4', 'user', 'content_item',     'ci-20', 'created', null,             'planned',        '{"title":"Weekend brunch post"}',                                           '2026-08-22T11:00:00Z');
